name: Bug report
description: Report a reproducible defect in codex-seo
title: "[bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this.
        For security issues, do not include exploit details here. Follow SECURITY.md.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is broken?
      placeholder: Short description of the problem
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact commands, inputs, and environment details
      placeholder: |
        1. Run ...
        2. Use ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or output
      description: Paste relevant output or traceback
      render: shell
  - type: input
    id: version
    attributes:
      label: Commit or version
      description: Git commit hash or release tag
      placeholder: e.g. 85b5e4d
