name: Feature request
description: Propose an improvement for codex-seo
title: "[feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should change and why?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other options you considered
  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: Who benefits and how this improves workflows
